name: Build
on:
 push:
  branches: [ main ]

jobs:
    build:
      runs-on: macos-latest
      steps:
      - name: Setup Theos
        uses: beerpiss/theos-action@v1.7.0
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: MEMO_TARGET=iphoneos-arm64e make luajit-package
