name: Build
on:
 push:
  branches: [ main ]

jobs:
    build:
      runs-on: macos-11
      steps:
      - name: Install Procursus
        uses: PureCyan/procursus-action@0.0.1
        with:
          packages: autoconf automake autopoint bash bison cmake curl docbook-xml docbook-xsl fakeroot findutils flex gawk git gnupg grep groff gzip ldid libtool make ncurses-bin openssl patch pkg-config po4a python3 sed tar triehash xz-utils zstd
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: MEMO_TARGET=iphoneos-arm64e-rootless make luajit-package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
         path: /Users/runner/work/Procursus/Procursus/build_dist/iphoneos-arm64*/*/luajit/*.deb
          
